name: update

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y
      - run: sudo apt install -y jq
      - run: bash ./srcpkgs/rebos/update-rebos.sh
      - run: bash ./srcpkgs/brave-browser/update-brave.sh
      - run: bash ./srcpkgs/zen-browser/update-zen.sh
      - name: Commit update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Automated update"
          git push
